version: '3.8'
services:
  namenode:
    build: 
      context: .
      
    container_name: namenode
    ports:
      - "9870:9870" # Hadoop NameNode UI
      - "9000:9000" # Hadoop NameNode UI
      - "2222:22"   # SSH port mapping for NameNode
    volumes:
      - namenode-config:/opt/hadoop/etc/hadoop
      - namenode-data:/opt/hadoop/data
      - ./shared-data:/data
      - ./setup:/setup
      - shared-keys:/shared-keys
      - namenode-ssh:/root/.ssh
    networks:
      - hadoop-network

  datanode1:
    build: 
      context: .
    container_name: datanode1
    ports:
      - "9867:9864"
    volumes:
      - namenode-config:/opt/hadoop/etc/hadoop
      - datanode1-data:/opt/hadoop/data
      - ./setup:/setup
      - shared-keys:/shared-keys
      - datanode1-ssh:/root/.ssh
    networks:
      - hadoop-network

  datanode2:
    ports:
      - "9868:9864"
    build: 
      context: .
    container_name: datanode2
    volumes:
      - namenode-config:/opt/hadoop/etc/hadoop
      - datanode2-data:/opt/hadoop/data
      - ./setup:/setup
      - datanode2-ssh:/root/.ssh
      - shared-keys:/shared-keys
    networks:
      - hadoop-network

  pig-node:
    build:
      context: .
      dockerfile: Dockerfile.pig
    container_name: pig-node
    volumes:
      - namenode-config:/opt/hadoop/etc/hadoop
      - edge-node-ssh:/root/.ssh
      - shared-keys:/shared-keys
      - ./shared-data:/data
      - ./pig-scripts:/pig-scripts
    depends_on:
      - namenode
      - datanode1
      - datanode2
    command: >
      sh -c "while true; do sleep 1000; done"
    networks:
      - hadoop-network

volumes:
  namenode-config:
  namenode-data:
  shared-keys:
  datanode1-data:
  datanode2-data:
  namenode-ssh:
  datanode1-ssh:
  datanode2-ssh:
  datanode-keys:
  authorized-keys:
  edge-node-ssh:

networks:
  hadoop-network:
    driver: bridge
