version: '3.8'
services:
  namenode:
    build:
      context: .
      dockerfile: Dockerfile.namenode
      
    container_name: namenode
    ports:
      - "9870:9870" # Hadoop NameNode UI
      - "9000:9000" # Hadoop NameNode UI
      - "2222:22"   # SSH port mapping for NameNode
    volumes:
      - namenode-config:/opt/hadoop/etc/hadoop
      - namenode-data:/opt/hadoop/data
      - ./shared-data:/data
      - ./setup:/setup
      - shared-keys:/shared-keys
      - namenode-ssh:/root/.ssh
    networks:
      - hadoop-network

  datanode1:
    build:
      context: .
      dockerfile: Dockerfile.datanode
    container_name: datanode1
    ports:
      - "9867:9864"
    volumes:
      - namenode-config:/opt/hadoop/etc/hadoop
      - datanode1-data:/opt/hadoop/data
      - ./setup:/setup
      - shared-keys:/shared-keys
      - datanode1-ssh:/root/.ssh
    networks:
      - hadoop-network

  datanode2:
    build:
      context: .
      dockerfile: Dockerfile.datanode
    container_name: datanode2
    ports:
      - "9868:9864"
    volumes:
      - namenode-config:/opt/hadoop/etc/hadoop
      - datanode2-data:/opt/hadoop/data
      - ./setup:/setup
      - datanode2-ssh:/root/.ssh
      - shared-keys:/shared-keys
    networks:
      - hadoop-network

volumes:
  namenode-config:
  namenode-data:
  shared-keys:
  datanode1-data:
  datanode2-data:
  namenode-ssh:
  datanode1-ssh:
  datanode2-ssh:

networks:
  hadoop-network:
    driver: bridge
